// selectors.js — единый хаб селекторов + fallbacks (фаза 3)
const MLS_SELECTORS = {
  feed: ['div[role="feed"]'],
  cardLink: ["a.hfpxzc", 'a[href*="/maps/place"]'],
  name: ["h1.DUwDvf", 'div[role="main"] h1'],
  category: ["button.DkEaL", 'button[jsaction*="category"]'],
  address: [
    'button[data-item-id="address"]',
    'button[data-item-id*="address"]',
    'button[aria-label*="Address"]',
    'button[aria-label*="Adresse"]',
  ],
  phone: [
    'button[data-item-id^="phone:tel:"]',
    'button[data-item-id*="phone:tel"]',
    'button[data-item-id*="phone"]',
    'a[href^="tel:"]',
    'a[data-item-id^="phone:tel:"]',
    'button[aria-label*="Phone"]',
    'button[aria-label*="Téléphone"]',
    'button[aria-label*="Telephone"]',
    'button[aria-label*="Appeler"]',
    'button[aria-label*="Call"]',
    '[data-tooltip*="phone" i]',
    '[jsaction*="pane.phone"]',
  ],
  website: [
    'a[data-item-id="authority"]',
    'a[data-item-id*="authority"]',
    'a[aria-label*="Website"]',
    'a[aria-label*="Site web"]',
  ],
  rating: ['div.F7nice span[aria-hidden="true"]'],
  reviews: [
    'div.F7nice span[aria-label*="review"]',
    'div.F7nice span[aria-label*="avis"]',
    'span[aria-label*="avis"]',
  ],
  back: [
    'button[aria-label="Back"]',
    'button[aria-label="Retour"]',
    'button[aria-label="Назад"]',
    'button[aria-label*="Back"]',
    'button[aria-label*="Retour"]',
    'button[jsaction*="back"]',
  ],
  hours: [
    'button[data-item-id="oh"]',
    '[aria-label*="Hours"]',
    '[aria-label*="Horaires"]',
    'div[aria-label*="Hours"]',
    'div[aria-label*="Horaires"]',
  ],
  openNow: [
    'span[aria-label*="Open"]',
    'span[aria-label*="Closed"]',
    'span[aria-label*="Ouvert"]',
    'span[aria-label*="Fermé"]',
    'div.o0Svhf',
  ],
  email: ['a[href^="mailto:"]'],
  plusCode: [
    'button[data-item-id="oloc"]',
    'button[aria-label*="Plus code"]',
  ],
  price: ['span[aria-label*="Price"]', 'span[aria-label*="Prix"]'],
  sponsored: ["Sponsored", "Sponsorisé", "Annonce", "Promoted", "Ad ·", "Publicité"],
  captcha: ["unusual traffic", "sorry/index", "recaptcha", "/sorry/"],
};
